### PR TITLE
Simplify configuration of the gnustep-2.0 ABI

### PR DESCRIPTION
**Pull request by ngrewe**
Configuring gnustep-make for the gnustep-2.0 ABI with the ng-gnu-gnu library combo is currently way more difficult than it should be. This PR improves on that in the following ways:

* A `--with-runtime-abi` allows selecting the ABI explicitly at configure time (the existing  `RUNTIME_VERSION` mechanism continues to be supported
* If an Objective-C runtime library is already installed, the configure script will now detect whether compiler and runtime support the gnustep-2.0 ABI and upgrade the runtime version appropriately if the ng-gnu-gnu library combo is selected
* The new ABI can trigger a bug in ld.bfd where categories stop working. If the new ABI is in use, we now issue a warning if a linker is in use that might have this problem. (unfortunately, there is no simple way to test for the problem in the configure script -- simple programs won't trigger it)

Under the hood, I've restructured things a bit and pulled things out of the configure script into m4 macros. I think this improves the readability of `configure.ac` and improves ordering constraints through `AC_REQUIRES` (though many things are still ordering dependent, I'm afraid). One main point here is the `GS_CHECK_OBJC_RUNTIME` macro, which sets the CFLAGS/LDFLAGS etc. for the runtime in the following process:

* Firstly, check for the user-supplied `--with-objc-lib-flag` and use that if available
* Secondly (and only if the user didn't give an indication on the library), check whether libobjc provides a pkg-config file (we've recently added one), and use the values defined therein.
* Thirdly, if that fails, search through the installation domains for a pre-installed runtime library and compile the flags as necessary.

Other things I've pulled out into macros are the following:

* `GS_CHECK_GCC_VERSION`
* `GS_CHECK_CC_IS_CLANG`
* `GS_LIBRARY_COMBO`

Apart from the reorganisation, which I hope would have broken in obvious ways if it introduced major bugs, these changes should only affect users who explicitly select the ng-gnu-gnu library combo, and for those it should provide a quite improved OOTB experience.

Cheers,

Niels

@rmottola: I've added you as a reviewer because it would be very helpful if you could test-drive this branch on the platforms you care about. I'm hoping that it won't be an issue, but I'm more then happy to fix problems that might come up. Thanks!

### CODE REVIEW

**Comment by rmottola** [comment]
Niels! Thank you for the close-up.. It will take me a couple of days to test this week. I will switch to your branch and reconfigure & reinstall gnustep make and base

First thing, I can test it will not disturb the Obj-C-1.0 setup

**Comment by rmottola** [comment]
First issue: it breaks for me on the simplest setup: Linux amd64 with gcc 8.3 and gcc runtime.

../../Headers/Foundation/NSException.h:48:2: error: #error "gnustep-base is configured to use 'traditional' exceptions, but you are building for 'native' exceptions."
 #error  "gnustep-base is configured to use 'traditional' exceptions, but you are building for 'native' exceptions."

I did not specify "anything" regarding exceptions.

**Comment by ngrewe** [comment]
> First issue: it breaks for me on the simplest setup: Linux amd64 with gcc 8.3 and gcc runtime.

Interesting. My GCC test setup for this has been Ubuntu 18.04 on x86_64 with gcc 7.4 and the libobjc that comes with it.

> #error "gnustep-base is configured to use 'traditional' exceptions, but you are building for 'native' exceptions."

gnustep-make defaults to setjmp/longjmp exceptions if it fails to compile a test program that includes @try/@catch. That can easily happen if the compiler flags end up wrong, which points to the CFLAGS not being set correctly by the new `GS_CHECK_OBJC_RUNTIME` macro. Can you attach the config.log from gnustep-make?

Thanks!

Niels

**Comment by rmottola** [comment]
[config.log](https://github.com/gnustep/tools-make/files/3936569/config.log)

**Comment by ngrewe** [comment]
Thanks Riccardo!

From the config.log, it'd say that the gnustep-make configure script did the correct thing and enabled native exceptions after successfully probing for compiler support. So the question now is where that information get's lost. I've got a few more follow-up questions:

* Did you reconfigure (and rebuild/reinstall) gnustep-base after installing the new version of gnustep-make?
* What is the output of `gnustep-config --objc-flags`?
* What is the output of `grep USE_OBJC_EXCEPTIONS $(gnustep-config --variable=GNUSTEP_MAKEFILES)/config.make` (or the arch/lib-combo specific subdirectory if your installation is non-flattened)?

**Comment by rmottola** [comment]
Hi Niels,
I positively reconfigured base, but failed.

Output of gnustep-config is:
$ gnustep-config --objc-flags
-MMD -MP -DGNUSTEP -DGNUSTEP_BASE_LIBRARY=1 -DGNU_GUI_LIBRARY=1 -DGNU_RUNTIME=1 -DGNUSTEP_BASE_LIBRARY=1 -fno-strict-aliasing -fexceptions -fobjc-exceptions -D_NATIVE_OBJC_EXCEPTIONS -pthread -fPIC -Wall -DGSWARN -DGSDIAGNOSE -Wno-import -g -O2 -fconstant-string-class=NSConstantString -I. -I/home/multix/GNUstep/Library/Headers -I/Local/Library/Headers -I/System/Library/Headers

Interestingly - I did reinstall gnustep-make, then reconfigured and rebuilt base and it worked.
The only difference I can imagine is that this second attempt, I previously had sourced GNUstep.sh, however the first time I did not (simulating clean install). I will continue further tests on other machines too.
On this setup  build completed and GS seems to work fine now.

**Comment by rmottola** [comment]
Hi Niels,

with my clang setup, it things failed. I reconfigured and compilerd make-base-gui-back and then Ink.
Any app will issue:

Assertion failed: (l->size >= sizeof(struct objc_protocol_method_description)), function protocol_method_at_index, file /usr/ports/lang/libobjc2/work/libobjc2-0db500a/protocol.h, line 85.
Abort (core dumped)

% gnustep-config --objc-flags
-MMD -MP -DGNUSTEP -DGNUSTEP_BASE_LIBRARY=1 -DGNU_GUI_LIBRARY=1 -DGNU_RUNTIME=1 -DGNUSTEP_BASE_LIBRARY=1 -fno-strict-aliasing -fexceptions -fobjc-exceptions -D_NATIVE_OBJC_EXCEPTIONS -pthread -fPIC -Wall -DGSWARN -DGSDIAGNOSE -Wno-import -I/usr/local/include -fobjc-runtime=gcc -fconstant-string-class=NSConstantString -I. -I/home/multix/GNUstep/Library/Headers -I/Local/Library/Headers -I/System/Library/Headers -I/usr/local/include

what would you use for clang? we need to use libobjc2 of course, since it is the only available. In "gnu" mode? I don't know even if it works.

**Comment by ngrewe** [comment]
I think it would be really nice to directly switch to the ng-gnu-gnu library combo if we discover that we're compiling with clang and that the runtime supports it. The issue with that is that it would introduce a circular dependency: Currently we might need to know the library combo to find the runtime (because it will be part of the file system path for headers in a non-flattened filesystem layout), so we can't at the same time use information about the runtime library to determine the library combo.

> what would you use for clang? we need to use libobjc2 of course, since it is the only available.

You should be able to use the gcc runtime even with clang, as long as specify that clang should use the gcc runtime ABI (that's correctly specified in the cflags…)

> In "gnu" mode? I don't know even if it works.

libobjc2 is supposed to upgrade the data structures emitted by the compiler (in this case a protocol) to the in-memory representation it expects (unless support for old ABIs has been disabled, which happens on Windows or if you pass `-DOLDABI_COMPAT=0` when configuring libobjc2, but we can discount that option because it would manifest itself with a different error message). So in theory it should work -- but the behaviour you're seeing might point to a bug with that? I couldn't reproduce it with a simple test program, though. But that issue would be better discussed on the libobjc2 bug tracker.

**Comment by triplef** [comment]
This is great, thank you @ngrewe!

> I think it would be really nice to directly switch to the ng-gnu-gnu library combo if we discover that we're compiling with clang and that the runtime supports it. The issue with that is that it would introduce a circular dependency: Currently we might need to know the library combo to find the runtime (because it will be part of the file system path for headers in a non-flattened filesystem layout), so we can't at the same time use information about the runtime library to determine the library combo.

Indeed it would be. Just an idea: would it work / make sense to assume libobjc2 will be used when Clang is detected in order to auto-select ng-gnu-gnu, and force people who still want to use the GCC runtime to say so in a configure parameter?

I was also wondering if there’s a way to auto-detect libobjc without pkg-config – I just briefly tested this branch with the [Android toolchain](https://github.com/gnustep/tools-android), and libobjc was not detected in this cross-compiling scenario.

**Comment by ngrewe** [comment]
> Just an idea: would it work / make sense to assume libobjc2 will be used when Clang is detected in order to auto-select ng-gnu-gnu, and force people who still want to use the GCC runtime to say so in a configure parameter?

It's tempting, but I'm not entirely comfortable with making the decision about the library combo based on the compiler alone.

> I was also wondering if there’s a way to auto-detect libobjc without pkg-config – I just briefly tested this branch with the Android toolchain, and libobjc was not detected in this cross-compiling scenario.

Not sure about how cross-compiling affects this, but the usual way to cope with that would be to use the override environment variables provided by pkg-config's autoconf module (`./configure --help` should also tell you about those):

```
  libobjc_CFLAGS
              C compiler flags for libobjc, overriding pkg-config
  libobjc_LIBS
              linker flags for libobjc, overriding pkg-config
```

**Comment by rmottola** [comment]
Niels,

what options do I have? I tried passing --with-library-combo=ng-gnu-gnu but the problem persists! A fat segfault as soon as I try to start a program.

**Comment by rfm** [comment]
> On 10 Dec 2019, at 11:29, Niels Grewe <notifications@github.com> wrote:
> 
> I think it would be really nice to directly switch to the ng-gnu-gnu library combo if we discover that we're compiling with clang and that the runtime supports it.

I agree, but only for the case where we are doing a clean/fresh build (ie where we would not override the user's expectations/wishes).

So if the user supplied the --with-library-combo=... we should honor their request
And if there is no explicit command-line option specified, but we are building on a system where gnustep is already installed, we should use the library combo of that installed system

But yes, if neither of those cases apply, we should try to use ng-gnu-gnu if possible.

**Comment by rmottola** [comment]
Updates - The issues I am finding on FreeBSD/amd64 and Linux/i386 with ng-gnu-gnu are I think unrelated to this patch, although best would be to have them solved before confirming it.

Now I am testing OpenBSD/amd64 with ng-gnu-gnu (always set with library-combo).
Base linking fails with this:

` Linking subproject Additions ...
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
ld: error: attempted static link of dynamic object /usr/bin/../lib/libc++abi.so.1.0
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[4]: *** [/System/Library/Makefiles/Instance/subproject.make:61: obj/subproject.o] Error 1
`

**Comment by ngrewe** [comment]
>  I think it would be really nice to directly switch to the ng-gnu-gnu library combo if we discover that we're compiling with clang and that the runtime supports it.

I've now implemented this by doing an additional check for a working ‘ng’ runtime under the following conditions:

* No preexisting gnutstep-make installation on the system
* No explicit `--with-library-combo` flag supplied by the user
* The implicit default runtime lib for the system is ‘gnu’
* clang is the compiler in use

**Comment by ngrewe** [comment]
> Now I am testing OpenBSD/amd64 with ng-gnu-gnu (always set with library-combo).
Base linking fails with this:

Hey, @rmottola -- it would be helpful to know a bit more details about this failure:

* With which version of libobjc2 does this happen?
* What is the actual compiler/linker command line used by make? (`make messages=yes`)


That said, I have a suspicion about this: The current master version of libobjc2 now included a pkg-config file (`libobjc2.pc`), which declares an explicit dependency on the C++ runtime library if necessary. My guess is the following: when you configured libobjc2 an explicit path to the library (rather than just `-lc++abi`) ended up in the linker flags, which then _somehow_ propagates to the build of the Additions subproject.
That's still worrisome in and of itself, even if id did link that static version of libc++abi -- the subproject only does partial linkage, and at least on my command line, the linker command does not specify any library at all.

To verify this theory, you could revert libobjc2 to rev 28375c9 and reconfigure/reinstall gnustep-make. This will force it to do the traditional way of discovering the runtime library CFLAGS/LDFLAGS (by probing the installation domains).

**Comment by rmottola** [comment]
@ngrewe Actually...I recollect some more information.
I had an older version of libobjc2 (May 2). I did upgrade to current, had an issue and found some email I wrote David some months ago, about my issues on OpenBSD with clang.

If I do not specify anything when building libobjc2, except forcing clang to the compiler, I get this issue when building base:
`Making all for tool cvtenc...
 Linking tool cvtenc ...
ld: error: undefined symbol: _Unwind_Resume
>>> referenced by cvtenc.m:0
>>>               ./obj/cvtenc.obj/cvtenc.m.o:(gnustep_base_user_main)
`
the last attempt of compiling libobjc2 tried to include "-DCMAKE_EXE_LINKER_FLAGS=-lc++abi " which is perhaps why it was "fixed" by David? Now this option is not needed anymore.

But then while compiling base, I get the above error.
I tried adding `LDFLAGS=-lc++abi` to base configure and base compiles. I need it for gui, back and any program.
Sounds as a dirty solution to consolidate? Only partially.
Once everything looks compiled and linked, running a gui app fails:

`$ Ink
Floating point exception (core dumped) `

`Program received signal SIGFPE, Arithmetic exception.
0x00000ce70b51110f in ?? () from /usr/libexec/ld.so
(gdb) bt
#0  0x00000ce70b51110f in ?? () from /usr/libexec/ld.so
#1  0x00000ce6f46dd600 in ?? ()
#2  0x0000000000000000 in ?? ()`

This proves actually that this issue was present, in a slightly different form perhaps, before your branch.

**Comment by rmottola** [comment]
@ngrewe : would it make sense to automatically add the settings I had to apply to LDFLAGS to get OpenBSD work reliably?

I needed:

./configure --prefix=/ --with-layout=gnustep --with-library-combo=ng-gnu-gnu --with-tar=/usr/local/bin/gtar LDFLAGS=-fuse-ld=bfd 

the relevant part are the LDFLAGS.

or is it better to leave them to the end user? I would set a default and if somebody sets LDFLAGS not blindly add the linker (so give the option to test things with the gold linker too)

**Comment by ngrewe** [comment]
>  would it make sense to automatically add the settings I had to apply to LDFLAGS to get OpenBSD work reliably?

Of course, things working out of the box is preferable, but based on what criterion would we make the linker selection? There are a few issues here:

* Choosing GNU bfd (if it's available) isn't always the right choice. At least with the version I managed to get my hands on for testing, it wouldn't produce working binaries with the gnustep-2.0 ABI.
* Detecting the specific linker issues is not easy. They are hard to reproduce esp. in the setting of gnustep-make where you cannot assume that you have any part of the Objective-C toolchain already available.
* There are multiple ways to set the linker: the `LD` environment variable does very much the same thing as passing `-fuse-ld`. To me, it seems difficult to detect which to use in order not to override the user's intent. 

The PR includes a new check in the configure script that will emit a warning if you are configuring gnustep-make for the gnustep-2.0 ABI, and you're using the bfd linker – maybe we can extend that to cover the specific failure mode on OpenBSD (I assume the default linker there is `lld`, right? That one has known issues as well, so the safest variant might actually be `gold`…)

**Comment by rfm** [comment]
WMer4ged since this patch already seems good as it is (I've been using it for a while).
It would be good to improve linker handling, but the rest doesn't need to wait for that.

**Comment by triplef** [comment]
I just wanted to note that the current method of checking which linker is used (`$CC --print-prog-name=ld`) does not seem to work for me, as it always outputs the path to `ld` irrespective of the `LD` environment variable, which can be verified e.g. like this (tried on macOS building for Android and on Windows MinGW64):

```
$ LD=ld.gold clang --print-prog-name=ld
/usr/bin/ld
```

Also, as noted above, any `-fuse-ld` option in `LDFLAGS` is also currently not taken into consideration by the check.

Could we maybe instead just use `LD` if it is set, and otherwise check `LDFLAGS` against `-fuse-ld=(.+)`?

**Comment by rfm** [comment]
> On 26 Nov 2020, at 13:54, Frederik Seiffert <notifications@github.com> wrote:
> 
> 
> I just wanted to note that the current method of checking which linker is used ($CC --print-prog-name=ld) does not seem to work for me, as it always outputs the path to ld irrespective of the LD environment variable, which can be verified e.g. like this (tried on macOS building for Android and on Windows MinGW64):
> 
> $ LD=ld.gold clang --print-prog-name=ld
> /usr/bin/ld
> 
> Also, as noted above, any -fuse-ld option in LDFLAGS is also currently not taken into consideration by the check.
> 
> Could we maybe instead just use LD if it is set, and otherwise check LDFLAGS against -fuse-ld=(.+)?

I guess the rationale for  ($CC --print-prog-name=ld) is that gnustep-make seems to expect to use the compiler to link.

For instance, we pass flags to the linker using -Wl, to tell the compiler to pass them through, and if we sometimes invoke the linker directly we would need to detect that and set a variable to say whether we are using the linker rsather than the compiler, and then test that variable at any point where we are setting up linker flags so that we set up the flags with the -Wl, prefix or without depending on whether we are passing them via the compiler.  There may be other things that would need to be changed in order to invoke a linker directly too, so I don't really know how much might be involved.

However, as long as we are using the compiler to link, it certainly seems that we should take int account -fuse-ld= in LDFLAGS.

**Comment by triplef** [comment]
> I guess the rationale for  ($CC --print-prog-name=ld) is that gnustep-make seems to expect to use the compiler to link.

Yeah good point. That being the case I guess `LD` will not be used anyway.

> However, as long as we are using the compiler to link, it certainly seems that we should take int account -fuse-ld= in LDFLAGS.

Exactly. So then we should probably first check for `-fuse-ld` and otherwise fall back to `$CC --print-prog-name=ld`?

**Pull request merged**
