### PR TITLE
since newer autoconf detects linux-musl as separate, try to support it

### PR DESCRIPTION
**Pull request by rmottola**
These are the main impacts which I found, seems to work already.

### CODE REVIEW

**Comment by fredkiefer** [comment]
This works and is very clean. But I am not convinced that the original workaround to switch back to linux-gnu in the clean-os.sh isn't the saver solution. Whenever there is a switch in any makefile, either here or in our libraries or even applications, we need to make sure to support this obscure OS.

**Comment by rmottola** [comment]
@fredkiefer I understand your point. On the other side, my reasoning was not to hide a difference in platform that is detected: it is more work, since perhaps I missed other spots of change, but it could now or in the future make easier to have and use a difference, so I prefer going this route. I wonder @rfm ?
It is not just a single linux distribution but a whole family - not relying on the GNU libc. There are/were others. Also perhaps other unix systems.

https://wiki.musl-libc.org/projects-using-musl.html

I have no idea how hybrids have to be configured, e.g. Debian with musl, could be interesting.

**Comment by rmottola** [comment]
after conversation with @rfm, we made common code using a variable. This way the os triplet linux-musl gets preserved, but can be used as linux.
I tested as no-regression on Linux, on GNU/Hurd and tested that on linux-musl works.

Possibly we can then also unite some android-linux stuff later.
I think it is fine now.

**Comment by rmottola** [comment]
tested on Linux/musl, Linux glibc standard, GNU HURD, NetBSD.
May I merge or can you, @rfm @fredkiefer ?

**Review by rfm — APPROVED** [review]
Looks fine for you to merge.

**Pull request merged**
